[clog]
repository = "https://github.com/quentinlesceller/redigo"
subtitle = "Release Notes"
from-latest-tag = true

[sections]
"Refactors" = ["refactor"]
"Chores" = ["chore"]
"Continuous Integration" = ["ci"]
"Improvements" = ["imp", "improvement"]
"Features" = ["feat", "feature"]
"Legacy" = ["legacy"]
"QA" = ["qa", "test"]
"Documentation" = ["doc", "docs"]
